spring.datasource.url=jdbc:mysql://localhost:3306/shoe_store
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Cấu hình VNPAY Sandbox (Môi trường thử nghiệm)

vnp.pay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.return.url=http://localhost:8080/payment/vnpay/return

vnp.tmn.code=5HTVUQOW
vnp.hash.secret=NCUHA2KD478O2EG21JX1N1H0E5T855Z1

vnp.api.url=https://sandbox.vnpayment.vn/merchant_webapi/api.html
